# Generated by Django 4.2.4 on 2023-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/patients'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
