# Generated by Django 4.2.4 on 2023-09-01 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientdetails_patient_patientdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
