# Generated by Django 4.2.4 on 2023-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
