# Generated by Django 4.2.4 on 2023-09-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_department_doctor_department'),
        ('patient', '0009_patientdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='department',
            field=models.ForeignKey(blank=True, default='Medicine', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.department'),
        ),
    ]
