# Generated by Django 4.2.4 on 2023-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patientdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(),
        ),
    ]
