# Generated by Django 4.2.4 on 2023-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_patientdetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
