# Generated by Django 4.2.4 on 2023-09-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientdetails_patient_patientdetails_address_and_more'),
        ('doctor', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='treating_doctors', to='patient.patientdetails'),
        ),
    ]
